### ISSUE TITLE
+5 or 5+

### ISSUE THREAD

**Issue by Arredatore** [Carrene/vue-notification-bell#6]
Will that be better to put the plus after the number. I personally fill the +5 as some number plus five, whereas 5+ as there are some numbers after the 5

**Comment by DannyFeliz** [comment]
This could be added as a prop 👍

**Comment by maryayi** [comment]
@Arredatore Maybe you are right. I have searched for it and found this page:
https://math.stackexchange.com/questions/480123/plus-sign-after-a-number-means

Like @DannyFeliz, I feel that we can add this feature as a prop, and I think it is better we keep your suggestion (postfix plus: 50+) as the default value

**Comment by maryayi** [comment]
This feature added to the new version :)
